export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";
export const UPDATE_USERS = "UPDATE_USERS";

export const GET_SELECTED_USER_BEGIN = "GET_SELECTED_USER_BEGIN";
export const GET_SELECTED_USER_SUCCESS = "GET_SELECTED_USER_SUCCESS";
export const GET_SELECTED_USER_FAILURE = "GET_SELECTED_USER_FAILURE";
